export const STOP_MOTORS_CHAR = 'Uw==\n'; /*Base64 for S*/
export const SHOULDER_BACKWARD_CHAR = 'Sw==\n'; /*Base64 for K*/
export const SHOULDER_FORWARD_CHAR = 'Tg==\n'; /*Base64 for N*/
export const ELBOW_BACKWARD_CHAR = 'Qg==\n'; /*Base64 for B*/
export const ELBOW_FORWARD_CHAR = 'Qw==\n'; /*Base64 for C*/
export const WRIST_BACKWARD_CHAR = 'WQ==\n'; /*Base64 for X*/
export const WRIST_FORWARD_CHAR = 'WA==\n'; /*Base64 for N*/
export const GRIPPER_OPEN_CHAR = 'Rw==\n'; /*Base64 for G*/
export const GRIPPER_CLOSE_CHAR = 'Ug==\n'; /*Base64 for R*/
export const FOREARM_CCW_CHAR = 'Rg==\n'; /*Base64 for F*/
export const FOREARM_CW_CHAR = 'QQ==\n'; /*Base64 for A*/
export const BASE_CCW_CHAR = 'Vg==\n'; /*Base64 for V*/
export const BASE_CW_CHAR = 'UQ==\n'; /*Base64 for Q*/
